sudo: required
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
- docker-compose ps
script:
- docker-compose run --rm verify sh -c "yarn && yarn test"
notifications:
  slack:
    secure: g6EyNfrERMFOD7xjgawHYALocTYHqYiNMjHos5KUM9gW6S5tuYZNZmd9xvSYtXF73hWkL9AtP+NWTdkG2kxUpuwoDBbyO4v8IABoFfm9/LtSKIR77H7+TeLm5tMDt5nHLIycjZphbJwKzRuspLshj+E7ipbGkTRxeXFJB1O6W9cOVwIm78BwPtXwFRIFwNzgfSXBZitKgZUr0yGmF9W11Pb+N7twdW2K2ZFhG6TpIEVmN9wlfqywv6fajg6tOXMHCUPxIwC8haUZRtF/1QHO/HZlwq3ZBqgUobbQFa+J8NZyBB5PU+zIliT172zSlho0mjqwVmdvRCT6qeVibvwMbyCgbJ0vfsJs+gFJ4txU1XJfJcy2YBzH6N7ETJj01vNp82rh85CO3TPgLHnlvhKZEU1yM/GipKpuqtstrKT9nyJni11NbvqyJeHw268O6ezGGDOZ510M3ogKN9hI1jEo9gVeAOD12MBBMwgdIfR9SzlV3moRlDDYDetvHpnP1ypyI40iUJ1FwkV1kKM+HXybDVd4q0delgYVxoDT2AYmCa2UKMvOhHANOvyhki75E25m1urpnoPkVKmZgMguWOqkhgJpgTlTlB+pdzCkUAIJ4+d+zHMovXCcMCz5HUFqKOWI4w+WoZZwVY0IycffFtl9iT2HwkTQDz2MFlYecZQyW/s=
