version: '2'
services:

  verify:
    image: registry.jincor.com/backend/verify:latest
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
    ports:
      - "3001"
      - "4001"
    volumes:
      - ./:/usr/src/app
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
