version: '2'
services:

  verify:
    image: registry.jincor.com/backend/verify:latest
    build:
        context: ./
        dockerfile: Dockerfile.prod
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
      THROTTLER_WHITE_LIST: "127.0.0.1"
    ports:
      - "3001"
      - "4001"
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
